### ISSUE TITLE
Cubic bezier infinite loop.

### ISSUE THREAD

**Issue by MatejJan** [w8r/bresenham-zingl#3]
I encountered a bug when placing the handles of a cubic bezier very close together.

```
bresenham.cubicBezier(0,0, 10, 0, 0, 5, 10, 5, (x, y) => console.log(x, y));
```

This will result in an infitie loop with the output:

```
0 0
1 0
2 0
3 0
4 1
5 2
5 3
5 4
6 4
6 4
6 4
6 4
6 4
6 4
…
```

When moving the handles apart as in

```
bresenham.cubicBezier(0,0, 10, 0, 0, 6, 10, 6, (x, y) => console.log(x, y));
```

the algorithm succeeds.

**Comment by MatejJan** [comment]
I've tracked down the issue to an incorrect unrolling of the loop inside `cubicBezierSeg`.

The original algorithm had:
```
    exit:
      for (pxy = 0, fx = fy = f; x0 != x3 && y0 != y3;) {
        setPixel(x0, y0);
        /* plot curve */
        do {                                  /* move sub-steps of one pixel */
          if (pxy == 0) if (dx > xy || dy < xy) break exit;
          /* confusing */
          if (pxy == 1) if (dx > 0 || dy < 0) break exit;
```

Which you changed to:
```
    var exit = false;
    for (pxy = xy, fx = fy = f; x0 != x3 && y0 != y3;) {
      setPixel(x0, y0); /* plot curve */
      do { /* move sub-steps of one pixel */
        if (dx > pxy || dy < pxy) {
          exit = true;
          break;
        }
```

The behavior of this whole section is now not equivalent to the original algorithm.

An easy fix is to just revert back to the original algorithm. Otherwise, if you insist on not using labeled breaks, you will need to investigate branching of the section further.

**Comment by MatejJan** [comment]
My initial assessment was incorrect. The problem is not how you eliminated the break label, but there was a bug/typo in the initialization of the for loop.

The original has:
```
for (pxy = 0
```
While you have:
```
for (pxy = xy
```
Setting `pxy` to `0` removes this problem.

I did see some other changes in this section from the way the original is written, but they do not contribute to the infinte loop problem and might not have any side effects.

**Comment by w8r** [comment]
i fixed this one, I believe. I misunderstood the `goto` jump in the initial code
